name    'saz-ccollect'
version '1.0.0'
source 'UNKNOWN'
author 'saz'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'Manage ccollect via Puppet'
project_page 'https://github.com/saz/puppet-ccollect'
